// Posts for the main page
export const FEATURED_POSTS_REQUEST = "FEATURED_POSTS_REQUEST";
export const FEATURED_POSTS_SUCCESS = "FEATURED_POSTS_SUCCESS";
export const FEATURED_POSTS_ERROR = "FEATURED_POSTS_ERROR";

export const TOGGLE_ADMIN_MODE = "TOGGLE_ADMIN_MODE";

// Register a user
export const USER_JOIN_REQUEST = "USER_JOIN_REQUEST";
export const USER_JOIN_ERROR = "USER_JOIN_ERROR";
export const USER_JOIN_SUCCESS = "USER_JOIN_SUCCESS";
export const USER_JOIN_RESET = "USER_JOIN_RESET";

// Sign In
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_ERROR = "USER_SIGNIN_ERROR";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";

// Create post
export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_ERROR = "POST_CREATE_ERROR";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

// Update Post
export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
export const POST_UPDATE_ERROR = "POST_UPDATE_ERROR";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_RESET = "POST_UPDATE_RESET";

// Delete Post
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_ERROR = "POST_DELETE_ERROR";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_RESET = "POST_DELETE_RESET";

// Change code looking
export const UPDATE_CODE_THEME = "UPDATE_CODE_THEME";
export const TOGGLE_SHOW_LINES_NUMBERS = "SHOW_LINES_NUMBERS";
export const TOGGLE_WRAP_LONG_LINES = "WRAP_LONG_LINES";

// Search
export const SEARCH_POSTS_REQUEST = "SEARCH_POSTS_REQUEST";
export const SEARCH_POSTS_ERROR = "SEARCH_POSTS_ERROR";
export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS";
export const SEARCH_POSTS_RESET = "SEARCH_POSTS_RESET";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR = "GET_ALL_POSTS_ERROR";
