// Posts for the main page
export const FEATURES_POSTS_REQUEST = "FEATURES_POSTS_REQUEST";
export const FEATURES_POSTS_SUCCESS = "FEATURES_POSTS_SUCCESS";
export const FEATURES_POSTS_ERROR = "FEATURES_POSTS_ERROR";
