// Posts for the main page
export const FEATURED_POSTS_REQUEST = "FEATURED_POSTS_REQUEST";
export const FEATURED_POSTS_SUCCESS = "FEATURED_POSTS_SUCCESS";
export const FEATURED_POSTS_ERROR = "FEATURED_POSTS_ERROR";

export const TOGGLE_ADMIN_MODE = "TOGGLE_ADMIN_MODE";

export const USER_JOIN_REQUEIST = "USER_JOIN_REQUEIST";
export const USER_JOIN_ERROR = "USER_JOIN_ERROR";
export const USER_JOIN_SUCCESS = "USER_JOIN_SUCCESS";
export const USER_JOIN_RESET = "USER_JOIN_RESET";
