export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_ERROR = "USER_SIGNIN_ERROR";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";

export const GET_CATEGORIES_REQUIES = "GET_CATEGORIES_REQUIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

export const UPDATE_CATEGORIES_REQUIES = "UPDATE_CATEGORIES_REQUIES";
export const UPDATE_CATEGORIES_SUCCESS = "UPDATE_CATEGORIES_SUCCESS";
export const UPDATE_CATEGORIES_ERROR = "UPDATE_CATEGORIES_ERROR";
export const UPDATE_CATEGORIES_RESET = "UPDATE_CATEGORIES_RESET";

export const CREATE_CATEGORIES_REQUIES = "CREATE_CATEGORIES_REQUIES";
export const CREATE_CATEGORIES_SUCCESS = "CREATE_CATEGORIES_SUCCESS";
export const CREATE_CATEGORIES_ERROR = "CREATE_CATEGORIES_ERROR";

export const DELETE_CATEGORIES_REQUIES = "DELETE_CATEGORIES_REQUIES";
export const DELETE_CATEGORIES_SUCCESS = "DELETE_CATEGORIES_SUCCESS";
export const DELETE_CATEGORIES_ERROR = "DELETE_CATEGORIES_ERROR";
